### PR TITLE
Update to arc 4, change to Yes (fixes #1)

### PR DESCRIPTION
**Pull request by mikemaccana**

### CODE REVIEW

**Comment by brianleroux** [comment]
sigh

**Comment by mikemaccana** [comment]
Now you've gotta deploy 😁

**Comment by brianleroux** [comment]
omg I have no idea which aws account this is in lol

**Comment by mikemaccana** [comment]
😂 Your`AWS_PROFILE` was `personal`, but maybe you have different ones. Would be fun to get deployed so I can convince @sambreed you actually accepted this!

**Pull request merged**
